common:
  seed: 100
  mm_precision: medium
  ckpt_path:

model:
  model_name: stabilityai/stable-diffusion-2-1-base
  train_text_encoder: false

trainer_params:
  accelerator: gpu
  precision: bf16-true
  devices: 1
  deterministic: true
  max_steps: 10000
  log_every_n_steps: 1
  gradient_clip_val: 1
  gradient_clip_algorithm: norm

image_logging:
  validation_prompt: 1girl, looking at viewer, upper body, twintails

dataset:
  type: image_crop
  data_csv: /ssd_first/malofeev/diffusion_diplom/datasets/fid10k_small_prompt.csv
  work_dir: /ssd_first/malofeev/diffusion_diplom/datasets/
  image_size: 512

dataloader:
  batch_size: 16
  num_workers: 8

optim:
  lr: 5e-5
  weight_decay: 1e-2
  scheduler: cosine
  scheduler_max_steps: 10000
  warmup_relative: 0.1
