common:
  seed: 100
  mm_precision: medium
  ckpt_path:

model:
  model_name: stabilityai/stable-diffusion-2-1-base
  train_text_encoder: true
  teacher_path:  # lightning_logs/baseline/checkpoints/epoch=0-step=50000.ckpt
  distill_alpha:  # 30
  ucg: 0.1

trainer_params:
  accelerator: gpu
  precision: bf16-true
  devices: 1
  deterministic: true
  max_steps: 50000
  log_every_n_steps: 1
  check_val_every_n_epoch: 0
  gradient_clip_val: 1
  gradient_clip_algorithm: norm
  # strategy: ddp

image_logging:
  every_n_steps: 4999
  validation_prompt: 1girl, looking at viewer, upper body, twintails

dataset:
  type: image_crop
  data_csv: ./datasets/fid10k_small_prompt.csv
  work_dir: ./datasets/
  image_size: 512

dataloader:
  batch_size: 16
  num_workers: 8

optim:
  lr: 5e-5
  weight_decay: 1e-2
  scheduler: cosine
  scheduler_max_steps: 100000
  warmup_relative: 0.1

logging:
  fid_images: 20

pruning:
  enable: false
